### ISSUE TITLE
Own IP

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/whmcs#12]
It's possible to add additional ips, so it would be nice if you can select a ip for your server.

So if you buy a server it has it own IP and isn't shared with others, like normal.

Also as config option?

**Comment by ulrichblock** [comment]
There is no need for such a feature that uses IPv4 abnormally. Create a new Product and label it premium. Add a list of masters/hosts which should run this premium service. Do allow as much game servers on the master as you have IPv4s on them. The API will assign the least used IP on creation.
