### ISSUE TITLE
Server suspend -> stop

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/whmcs#14]
If server suspend it should also be stopped.

**Comment by ulrichblock** [comment]
X4jf84BZ3YD!

**Comment by ulrichblock** [comment]
As so many times before, you seem to be the only one that is affected. So again, I cannot do a thing without the excact configuration and so on.

**Comment by DAThosting** [comment]
No I'm sure not the only one, and I can't understand whats exactly the problem in the system.
I asked you more than one times if you could check my system, also firstversion couldn't explain the problem.
A complete reinstall doesn't help anything, there are the same problems as before.
