### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/whmcs#17]
Functions like, (re)start/stop of servers and so on.

For (re)start and stop I used the API, but not the api from your module. should be implemented directly.

Console, WebFTP and the other Settings should also be duplicated to WHMCS directley.

**Comment by ulrichblock** [comment]
Would mean to reuild a webinterface inside WHMCS. The required amount of time is not worth it in my opinion. Plus you very likely will run into network issues at least for Console and FTP.
