### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by Tobi7889** [easy-wi/whmcs#19]
If i create a customer in WHMCS and create the product, it calls "Modul Befehlsfehler - No Easy-Wi API response". 

On recipent Server i see this error in logs:
**.***.**.*** - - [21/Mar/2017:09:17:13 +0100] "POST /api.php HTTP/1.0" 403 644 "-" "https://github.com/easy-wi/whmcs"

**Comment by Tobi7889** [comment]
PS: We use WHMCS 7.1.2

**Comment by ulrichblock** [comment]
Activate logger on WHMCS side and see what the response is.

**Comment by ulrichblock** [comment]
Might have been the same as #21 Closing as now reply.
