### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by metallicgloss** [easy-wi/whmcs#2]
Hello!
This isn't an issue at all, however, I just wanted to say I huge thank you for releasing this publically, as even though it may impact on First-Version's sales, it makes using this panel much more appealing.

**Comment by Thiritin** [comment]
Thank you Urich and First Version for releasing this for free, i think this is now the THANK YOU thread :+1:

**Comment by metallicgloss** [comment]
Just checking @MartinBecker, Is this the exact same version as the First-Version one? I have been waiting until I get another WHMCS licence to test it as I dont want to loose the data.

**Comment by itsescde** [comment]
+1 
A huge thanks to Ulrich and First Version.

**Comment by Paul20666** [comment]
Thanks from my side ;)

**Comment by timhah** [comment]
yes, thank you!
