### ISSUE TITLE
Webspace account creation / termination

### ISSUE THREAD

**Issue by konestar** [easy-wi/whmcs#20]
Nach Anlegen des Webspace (Fastdownload) Accounts über das WHMCS Addon, muss der Kunde erst über Easy-Wi ein Reinstall machen, bevor der Zugang funktioniert. Bei der Termination des Webspace-Accounts über WHMCS kommt die Meldung: "Module Command Error No webspace can be found with the given ID". 

Easy-WI v. 6.0.0
WHMCS v. 7.2.1
WHMCS  Easy-Wi Addon Stand: 27 Mar

Bei Gameserver, TS3 und MySQL funktioniert oben genanntes problemlos.

**Comment by ulrichblock** [comment]
Mach bitte den Debugger bei dem WHMCS Addon an. Die Aktion wiederholen und dann schau in das Activity Log. Welche Fehler tauchen auf`?

**Comment by konestar** [comment]
Folgendes wird im Activity Log ausgegeben nach dem Aktion durchgeführt wurde: https://pastebin.com/VHbwk9uX

**Comment by ulrichblock** [comment]
Mach bitte den Debugger auf Seiten von Easy-Wi an und wiederhole das Spiel. Ich kann erst einmal nichts Auffälliges sehen.

**Comment by konestar** [comment]
Wenn ich den debug in der config.php auf 1 setze, erhalte ich beim Versuch der Terminierung über WHMCS die Meldung

Module Command Error
No Easy-Wi API response

Ist der Debug auf 1 kommt wieder die Meldung "No webspace can be found with the given ID"
Obwohl der Webspace mit der entsprechenden Externel ID existiert und direkt über Easy-Wi auch gelöscht werden kann.

**Comment by ulrichblock** [comment]
Ich vermute mal wieder Ubuntu 16.04 und neuer und dazu MySQL 5.6. Weiter vermute ich, dass man im Log eine SQL Exception sehen kann. Was aber genau los ist, ist recht schwer zu sagen, weil man den Inhalt der Raw Response lesen müsste.
