### ISSUE TITLE
Raw response: 403 Forbidden: No valid api data Request IP is

### ISSUE THREAD

**Issue by johnsheppard33** [easy-wi/whmcs#21]
Hello,
I have a problem for link Easy-Wi and Whmcs, "Raw response: 403 Forbidden: No valid api data Request IP is"

Thank you for your help.

**Comment by johnsheppard33** [comment]
https://gyazo.com/8f6326d88cca5807d54307e115bc409e

**Comment by johnsheppard33** [comment]
And this ip is the former server i have try to install Easy-Wi

**Comment by johnsheppard33** [comment]
The new don't work, It's because update ?

**Comment by Headwipe** [comment]
I had the same Problem with my installation. I fixed it by changing the password which don't uses special chars like "%&$§". 

Second Problem could be that you didn't set the correct IP in the Easy-Wi Panel.

Hopefully this will help you too.

**Comment by johnsheppard33** [comment]
Thank you for reply, I have solve the problem : It's just my Ovh CDN.
