### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/whmcs#22]
Option hinzufügen um Gameservern eine oder mehrere Datenbanken bereit zu stellen, jedoch localhost.
Ein Bundle ist somit leider nicht möglich.

**Comment by ulrichblock** [comment]
Man kann bei WHMCS doch N Produkte zu einem Bundle zusammenfügen. Alles auf einem Host laufen zu lassen ist keine gute Sache. Deswegen verstehe ich das Anliegen nicht wirklich.

**Comment by DAThosting** [comment]
Zu einem Bundle zusammenfassen ist nicht das Problem.
Eine localhost Datenbank ist bei Gameservern weit besser als eine externe zu nehmen. Allein schon bzgl. den Latenzen.
Es geht nur darum eine oder mehrere Datenbanken mit dem gewünschten Server auf dem selben Master anzulegen. Wenn gelöscht wird müssen natürlich auch die Datenbanken wieder weg. Prinzipiell würde es reichen das ganze als Config Option anzugeben oder? Müsste nur mit in den Code geschrieben werden.

**Comment by DAThosting** [comment]
bump
