### ISSUE TITLE
Sync = No -> No Sync at all

### ISSUE THREAD

**Issue by fsedarkalex** [easy-wi/whmcs#25]
If you set sync to no it results in no users being synced at all on automation tasks.
If you manually process the order it will work but "on payment" it will fail:

```
An order has received its first payment but the automatic provisioning has failed and requires you to manually check & resolve.

Client ID: 2
Service ID: 3
Product/Service: TEST
Domain:
Error: User is not synced!

https://www.***.de/admin/
This notification was automatically generated by WHMCS
 https://www.***.de/ | log in to the admin area  

```

**Comment by ulrichblock** [comment]
That is the point of the option no sync. It is meant for the time during the installation/update or a migration.
