### ISSUE TITLE
Order Probleme

### ISSUE THREAD

**Issue by Thiritin** [easy-wi/whmcs#3]
Hi,

Ich möchte gerne einen Bug reporten.

Sobald ich das Easy-Wi Addon aktiviere kann ich keine Orders mehr löschen oder anderweitig ändern, ich erhalte immer nur einen HTTP ERROR 500.

Ich erhalte in der Apache error Datei keinen Fehler, die access.log habe ich hier.

```
[...]
action=delete&id=14&token=*******************************HTTP/1.1" 302 380 "https://shop.********.eu/admin/orders.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
***.***.92.*** - - [07/Aug/2016:02:18:06 +0200] "GET /admin/orders.php?filter=1 HTTP/1.1" 200 7935 "https://shop.*********.com/admin/orders.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[...]
```

Hat jemand das gleiche problem? Das Problem tritt bei allen Bestellungen auf.

Vielen dank :smile:

**Comment by Thiritin** [comment]
Behoben nachdem ich die hooks.php umbenannt habe.

**Comment by ulrichblock** [comment]
Und damit laufen die Hooks gar nicht. Ich hatte vergessen den Aufruf von:
`$easyWiObject->licenseCheck()`

Auszubauen
