### ISSUE TITLE
Data key does not exist: shorten, Not supported method or incomplete data

### ISSUE THREAD

**Issue by heislpeda** [easy-wi/whmcs#31]
Hello, i have a problem with whcms plugin easy wi

Es gab ein Problem beim Akzeptieren der Bestellung
Data key does not exist: shorten, Not supported method or incomplete data

why? please help me, its a big problem ;(

**Comment by ulrichblock** [comment]
Please provide debug logs. Set PHP to debug, so you have stack traces.

**Comment by heislpeda** [comment]
how to set the mode to debug???

**Comment by ghost** [comment]
For EasyWi:

/easywi/stuff/config.php 

Change 

$debug = 0;
to 
$debug = 1; 

For WHMCS:

In the Settings
configgeneral.php#tab12

Grüße

**Comment by ulrichblock** [comment]
Closing as no further feedback provided
