### ISSUE TITLE
user werden nicht richtig gesynct

### ISSUE THREAD

**Issue by dranelixx** [easy-wi/whmcs#33]
Hallo habe dass Problem 1. dass dass ftp password nicht direkt übernommen wird ? heißt dem user wird ein falsches password angezeigt

2. es wird kein server installiert ordner des users exestiert mehr aber nicht

**Comment by DraneLixX** [comment]
und dass einzigste was ein bisschen erfolg verspricht ist dass es mir ab und zu anzeigt "sie werden in 3 sekunden weitergeleitet" es passiert aber nix bleibe im login screen ?

**Comment by akonopcz** [comment]
reinstall bringt auch nix ? auch nicht per admin user???

**Comment by DAThosting** [comment]
Das ist doch ein Easy-Wi Problem bei dir und hat meines Erachtens nach nichts mit WHMCS zu tun oder dem Modul.

**Comment by ulrichblock** [comment]
Duplicate of #30
