### ISSUE TITLE
gameserver install über whmcs fehlerhaft

### ISSUE THREAD

**Issue by dranelixx** [easy-wi/whmcs#34]
Hallo ich habe dass problem dass das whmcs die gameserver oder was weiß ich irg nicht richtig Insalliert
unzwar wenn ich über easywi gamepanel den server einrichte alles super funzt alles aber wenn ich es über whmcs mache startet der server nicht und unteranderem erstellt er keine screenlog.0 und wenn ich es selber mache löscht die sich nach paar sekunden warum auch immer?

**Comment by akonopcz** [comment]
cronjob funktionieren auch alle

**Comment by akonopcz** [comment]
Unteranderem wenn ich ein backup erstelle alles kein problem aber wenn er es wiederherstellen soll passiert nix wenn du logs brauchst sagst du bescheid wo ich welche finden kann habe nämlich keine gefunden

**Comment by ulrichblock** [comment]
Du vermengst anscheinened ein paar Dinge. Was genau, ist sau schwer zu lesen, weil du ohne Punkt und Komma, sowie Großbuchstaben schreibst. Nach 2 Versuchen den Text zu lesen habe ich aufgegeben,

**Comment by danir-de** [comment]
@DraneLixX Versuche erst einmal das Script in der Shell direkt auf dem Server auszuführen, optimalerweise bekommst mit den Berechtigungen des Easy-WI Nutzers. 

Du dürftest dann eine Fehlermeldung erhalten, wahrscheinlich ist die Binary einfach nicht ausführbar.
