### ISSUE TITLE
Broken link in WHMCS - User is not synced!

### ISSUE THREAD

**Issue by ElDivines** [easy-wi/whmcs#4]
Hello, even if i syncronize them, whmcs or easy wi api doesn't recognize them.
Even when i syncronize them, the modules say " Syncronized " then i try to create an order and " User is not synced! " can  you help me?

**Comment by ulrichblock** [comment]
If it is not working in general, it might be an error with your setup. You might want to activate the debug setting at the addon at WHMCS and check the activity log. It now will contain all infos about the connections.

**Comment by ElDivines** [comment]
I did, and there are any log about the module

**Comment by ulrichblock** [comment]
In that case you must be looking in the wrong log. If you have activated the logging at the addon and tried to sync you will have log entries, no matter of success.
