### ISSUE TITLE
Problem with delivrery

### ISSUE THREAD

**Issue by YaZhok** [easy-wi/whmcs#40]
Hi everybody ! 

I have a problem with whmcs and delivery system.

I' accept the command and receive this message : Cannot find free root server with given shorten

This is very strange and i'm not understand this error (user exist in database).

if you know this error, please help me !

Cordially !

**Comment by danir-de** [comment]
Hi,

the problem is, that the module contacts easywi and easywi then looks for a master server, that has 

1. enough available RAM
2. enough available CPU cores
3. enough available storage
4. enough available masterserver slots
5. the requested gameserver image installed

If one of these fails, then your error message pops up.

Greetings

**Comment by YaZhok** [comment]
Hi @chronicals

Thansk for your help

I’m looking your comment and all things are ok!

**Comment by danir-de** [comment]
@YaZhok Try to create the server with minimal ressources (1 mb ram, 1mb space, 1 core and a game template that is installed on the root server with the correct root server id set in the whmcs product)

**Comment by YaZhok** [comment]
Hi @chronicals 
Here are screenshots of the product configuration + from easy-Wi
be aware that user synchronization is done
![Capture d’écran du 2019-04-18 23-57-36](https://user-images.githubusercontent.com/25747917/56393882-ef5aba00-6235-11e9-83bd-760278d6030b.png)
![Capture d’écran du 2019-04-18 23-57-54](https://user-images.githubusercontent.com/25747917/56393883-eff35080-6235-11e9-8cb5-85bcd14f44ea.png)
![Capture d’écran du 2019-04-18 23-58-08](https://user-images.githubusercontent.com/25747917/56393884-eff35080-6235-11e9-91db-f4ae5c6b2e0e.png)
![Capture d’écran du 2019-04-18 23-58-32](https://user-images.githubusercontent.com/25747917/56393885-eff35080-6235-11e9-94f3-695fbf5ece2f.png)
![Capture d’écran du 2019-04-18 23-58-44](https://user-images.githubusercontent.com/25747917/56393886-eff35080-6235-11e9-870c-6a1e23e5b41f.png)

**Comment by danir-de** [comment]
Could you please also make a screenshot from the EasyWI Master overview and detail page?

Edit: 
Also please try a screenshot addon for better readability: https://addons.mozilla.org/de/firefox/addon/fireshot/

**Comment by YaZhok** [comment]
Hi @chronicals 
(the problem with screenshots is the fault of ubuntu ...)

I managed to set up the automatic delivery system! 

Thank's Again !
