### ISSUE TITLE
Kommunikation WHMCS und Easy-Wi Api

### ISSUE THREAD

**Issue by terraisoliert** [easy-wi/whmcs#42]
Hallo,

wir möchten unser Easy-Wi mit WHMCS verbinden.
WHMCS haben wir auf einer Debian-Stretch VM installiert in der Version 7.7.1.

Nach der Einrichtung versuchten wir testweise Benutzer zu synchronisieren, bzw. von EasyWi abgefragen zu lassen. Bei der Synchronisierung zwischen WHMCS und EasyWi steht zwar "Sync succeeded", aber ich sehe keinen neuen Benutzer in der Admin-Oberfläche in Easy-Wi.
Bei der Abfrage von Easy-Wi-User erscheint jedesmal die Meldung "Raw response: 403 Forbidden: No valid api data Request IP is: xxx.xxx.xxx.xxx".

Offentsichtlich bekommt man von der API eine Antwort. Allerdings weis ich nun nicht ob das Problem die API von Easy-Wi ist, oder das WHMCS-Plugin..
Über die Apache Access-Log sehe ich zwar die Verbindung zur api.php und den selben Error 403, aber das wars auch schon.
"xxx.xxx.xxx.xxx - - [14/Jul/2019:23:12:36 +0200] "POST /api.php HTTP/1.1" 403 417
"

Deswegen meine Frage, funktioniert dieses Plugin überhaupt? Bzw. hat jemand Tipps?

**Comment by Thiritin** [comment]
Das Plugin Funktioniert. Hast du in Easy-WI die IP gewhitelistet deines WHMCS-Servers?
