### ISSUE TITLE
Serverstandort

### ISSUE THREAD

**Issue by ghost** [easy-wi/whmcs#7]
Hallo, 
ist es möglich das beim Bestellen der Kunde den Server Standort wählen kann?
z.B Frankreich, Deutschland, Österreich usw...

Eventuell mit Option Value... Easy-Wi ID 
Grüße

**Comment by ulrichblock** [comment]
Derzeit nur dadurch, dass man Produkte je Rechenzentrum definiert. Nicht aber durch eine Auswahl wie einem Drop Down/Select.
