### ISSUE TITLE
Löschen von Servern

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/whmcs#9]
Ich weiß ich könnte damit nerven @ulrichblock , aber langsam ist es nur noch anstrengend jeden Server einzeln manuell zu löschen, weil das Modul immer einen No Easy-Wi.com API Response ausspuckt.

Gerne würde ich wissen wie der Fehler zustande kommen kann, denn ein Server erstellen, verändern oder deaktivieren ist ohne Probleme möglich.

Die WHMCS Activity Logs: http://pastebin.com/JQP6DyFf
EW Module Config: http://prntscr.com/dm8mam

Ein erweitertes Error Reporting der API wäre hier evtl. auch hilfreich, da ich nicht nachvollziehen kann warum das Problem auftritt.

**Comment by ulrichblock** [comment]
Und wieder einmal kann man dir nicht helfen. Keine Ahnung, was für Versionen du nutzt, ob per Debugger usw. getraced wurde, welches OS, welche Firewalls, welche Runtime usw., usw.

**Comment by DAThosting** [comment]
Easy-Wi Version: 5.39 DEV
WHMCS Version: 6.3.1
PHP 5.6.29 Apache
OS: Deb8 minimal
Runtime testweise auf 300 => 5mins

Wie ich den Debugger da nutzen soll ist mir unbekannt, da ich ja über die API bzw. das Modul auf Easy-Wi zugreife.

Firewalls blockieren keine relevanten Ports o.ä., da ja erstellen, verändern, deaktivieren und aktivieren ohne irgendwelche Probleme funktioniert.

**Comment by ulrichblock** [comment]
Ich kann den Code nicht validieren, da der DEV Server von WHMCS gerade down ist. Ich habe das Log erheben verändert, weil ich vermute, dass "User Löschen -> Nein" die Ursache sein könnte. Wenn es das wirklich ist, dann ist der Fix im obrigen Commit bereits enthalten.

**Comment by DAThosting** [comment]
Super es geht, dankeschön schonmal für die Mühe!
